# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main2:
            pattern:    ^/test
            http_basic: ~
            provider: our_db_provider
        main:
            anonymous: ~
            form_login:
                default_target_path: default_security_target
                always_use_default_target_path: true
                use_referer: true
                target_path_parameter: redirect_url
                failure_path: login_failure
                login_path: login
                check_path: login
        secured_area:
                form_login:
                    csrf_token_generator: security.csrf.token_manager   
                    csrf_parameter: _csrf_security_token
                    csrf_token_id: a_private_string

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }